device: ???
z_size: 32
c_size: 16
encoder: "cnn"
arencoder: "gru"
look_ahead_layer: "linear"
look_ahead: 12
batch_size: 8
epochs: 100
update_interval: 50
tsne_interval: 10000
log_output: true
N: 10
shuffle: true
tsne:
  perplexity: 30
  n_iter: 50000
  learning_rate: 10
optim:
  name: "Adam"
  lr: 0.0001
negative_sample_selector: "random"