device: ???
z_size: 512
c_size: 256
encoder: "cnn_huge"
arencoder: "gru"
look_ahead_layer: "linear"
look_ahead: 12
batch_size: 8
epochs: 100
update_interval: 50
tsne_interval: 10000
log_output: true
N: 10
shuffle: true
saved_model: null
generate_tsne_only: false
optim:
  name: "Adam"
  lr: 0.0001
negative_sample_selector: "random"
embedding_generator: "mean_c"
