timedelta: 5
is_labelled: True
directory: "data/elephants"
name: "continuous_image_elephant"
sampling_frequency: 200
channels: ???
grace_period: 60
num_classes: 2
resize: False
size: 64
kenya_data: False
frequency_min: 10
frequency_max: 50
n_fft: 400
use_collate_fn: True
hop_length: 1
win_length: 199
stations:
  - "EEL11"
  - "ETA00"